/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/rolling": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 롤링 뉴스 데이터 반환 (left 5개, right 5개)
     * @description 롤링 기능에 쓰이는 뉴스 데이터를 반환합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              left?: Record<string, never>[];
              right?: Record<string, never>[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/newsstand": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모든 뉴스 스탠드 언론사 정보 반환 (기사 데이터 미포함)
     * @description 모든 뉴스 스탠드 언론사에 대한 정보를 반환합니다. 리스트뷰에 쓰일 개별 기사 데이터가 필요하면 /api/newsstand/{pid} 엔드포인트를 사용하세요.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              blocks?: {
                /** @description 언론사 ID */
                pid?: string;
                /** @description 언론사 이름 */
                name?: string;
                /**
                 * @description 언론사 타입
                 * @enum {string}
                 */
                pressType?: "major" | "minor" | "subs" | null;
                logoLight?: {
                  url?: string;
                };
                logoDark?: {
                  url?: string;
                };
                showThumbnailView?: boolean;
                showListView?: boolean;
                excludeInPaging?: boolean;
                positionForPaging?: number;
                realtime?: boolean;
                regDate?: string;
              }[];
              /** @description 전체 언론사 개수 */
              totalCount?: number;
              /**
               * @description 카테고리별 언론사 PID 목록
               * @example [
               *       {
               *         "label": "종합/경제",
               *         "pids": [
               *           "032",
               *           "005",
               *           "944",
               *           "079",
               *           "327"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "방송/통신",
               *         "pids": [
               *           "356",
               *           "908",
               *           "938",
               *           "984",
               *           "911"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "IT",
               *         "pids": [
               *           "421",
               *           "003",
               *           "916",
               *           "422",
               *           "376"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "영자지",
               *         "pids": [
               *           "910",
               *           "138",
               *           "029",
               *           "953",
               *           "952"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "스포츠/연예",
               *         "pids": [
               *           "681",
               *           "330",
               *           "040",
               *           "044",
               *           "326"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "매거진/전문지",
               *         "pids": [
               *           "830",
               *           "447",
               *           "529",
               *           "117",
               *           "108"
               *         ],
               *         "count": 5
               *       },
               *       {
               *         "label": "지역",
               *         "pids": [
               *           "335",
               *           "087",
               *           "688",
               *           "339",
               *           "821"
               *         ],
               *         "count": 5
               *       }
               *     ]
               */
              catePidList?: {
                /** @description 카테고리 이름 */
                label?: string;
                /** @description 해당 카테고리의 언론사 PID 목록 */
                pids?: string[];
                /** @description 해당 카테고리의 언론사 개수 */
                count?: number;
              }[];
            };
          };
        };
        /** @description Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/newsstand/{pid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 뉴스 스탠드 언론사 정보 반환 (기사 데이터 포함)
     * @description 특정 뉴스 스탠드 언론사에 대한 정보를 반환합니다. 리스트 뷰에서 언론사 하나 넘어갈 때 마다 호출하시면 됩니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description 언론사 ID (예: 032, 055) */
          pid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description 언론사 ID */
              pid?: string;
              /** @description 언론사 이름 */
              name?: string;
              /**
               * @description 언론사 타입
               * @enum {string}
               */
              pressType?: "major" | "minor" | "subs" | null;
              logoLight?: {
                url?: string;
              };
              logoDark?: {
                url?: string;
              };
              showThumbnailView?: boolean;
              showListView?: boolean;
              excludeInPaging?: boolean;
              positionForPaging?: number;
              realtime?: boolean;
              regDate?: string;
              /** @description 기사 목록 */
              materials?: {
                "@type"?: string;
                gdid?: string | null;
                title?: string;
                url?: string;
                aid?: string | null;
                image?: {
                  url?: string;
                } | null;
                _id?: string;
              }[];
              /** @description 기사 개수 */
              materialsCount?: number;
            };
          };
        };
        /** @description Press not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error?: string;
            };
          };
        };
        /** @description Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 현재 사용자의 구독 목록 조회
     * @description 현재 로그인된(쿠키 기반) 사용자가 구독한 언론사 PID 목록을 반환합니다. 언론사 상세 정보는 /api/newsstand 엔드포인트와 조합하여 사용하세요.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description 구독한 언론사 PID 목록 */
              pids?: string[];
              /** @description 구독한 언론사 개수 */
              count?: number;
            };
          };
        };
        /** @description Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Failed to fetch subscriptions */
              error?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/subscribe/{pid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 언론사 구독 추가
     * @description 현재 사용자가 특정 언론사를 구독 목록에 추가합니다. 구독된 언론사 정보를 리턴합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description 구독할 언론사 ID (예: 032, 055) */
          pid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description 구독 추가 성공 여부 */
              success?: boolean;
              /**
               * @description 응답 메시지
               * @example Subscription added
               */
              message?: string;
              /** @description 구독된 언론사 ID */
              pid?: string;
              /** @description 구독된 언론사 이름 */
              name?: string;
              /**
               * @description 언론사 타입
               * @enum {string}
               */
              pressType?: "major" | "minor" | "subs" | null;
              logoLight?: {
                /** @description 라이트 모드 로고 URL */
                url?: string;
              };
              logoDark?: {
                /** @description 다크 모드 로고 URL */
                url?: string;
              };
              /** @description 구독 시각 (Unix timestamp) */
              subscribedAt?: number;
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Press not found */
              error?: string;
            };
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Already subscribed */
              error?: string;
              /** @example 이미 구독 중인 언론사입니다. */
              message?: string;
            };
          };
        };
        /** @description Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Failed to add subscription */
              error?: string;
            };
          };
        };
      };
    };
    /**
     * 언론사 구독 해제
     * @description 현재 사용자가 특정 언론사의 구독을 해제합니다. 삭제된 언론사 정보를 리턴합니다.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description 구독 해제할 언론사 ID (예: 032, 055) */
          pid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description 구독 해제 성공 여부 */
              success?: boolean;
              /**
               * @description 응답 메시지
               * @example Subscription removed
               */
              message?: string;
              /** @description 구독 해제된 언론사 ID */
              pid?: string;
              /** @description 구독 해제된 언론사 이름 */
              name?: string;
              /**
               * @description 언론사 타입
               * @enum {string}
               */
              pressType?: "major" | "minor" | "subs" | null;
              logoLight?: {
                /** @description 라이트 모드 로고 URL */
                url?: string;
              };
              logoDark?: {
                /** @description 다크 모드 로고 URL */
                url?: string;
              };
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Subscription not found */
              error?: string;
              /** @example 구독 중이 아닌 언론사입니다. */
              message?: string;
            };
          };
        };
        /** @description Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Failed to remove subscription */
              error?: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
